Feature/user user cf redis pipeline
mathun3003/quotes-recommender pull request #29
Opened 2024-01-21 11:44 UTC by mathun3003

User-User Collaborative Filtering klappt jetzt. Allerdings sollten wir nochmal bzgl. Performance schauen. Hier hätte ich folgende Vorschläge:

- Sets löschen, die weniger als N Elemente haben (=weniger Iterationen durch `scan_iter` und nachfolgende Schleifen)
- Datentyp wechsel von Sets zu Sorted Sets, da man hier `ZRANGEBYSCORE` verwenden kann zum filtern

Sofern die Performance für euch kein Problem darstellt, könenn wir es auch so lassen. Ich kann allerdings nicht abschätzen, wie sich die Laufzeit verhält bei noch mehr Daten...

2024-01-22 10:56 UTC, Andyzilong requested changes
Good job :+1:

2024-01-22 10:56 UTC, Andyzilong commented on quotes_recommender/quote_scraper/spiders/goodreads_spider.py
> -    name = 'goodreads-spider'
Bitte das auch einmal für den AZ-Spider machen, damit wir das einheitlich haben :)

2024-01-22 10:56 UTC, Andyzilong commented on quotes_recommender/ui/recommendations.py
>      if (not likes) and (not dislikes):
Präferenzsache, ich hätte not(likes or dislikes) verwendet :D

2024-01-22 10:56 UTC, Andyzilong commented on quotes_recommender/user_store/user_store_redis.py
> +        # most_similar_user = next(iter(max_user))
Falls diese aktuelle vereinfachte Form funktioniert, dann können die auskommentierten Codes auch weg oder? :)

2024-01-22 10:56 UTC, Andyzilong commented on quotes_recommender/user_store/user_store_redis.py
> +    def clean_up_user_store(self, threshold: int = DEFAULT_SIMILAR_PREFERENCE) -> None:
Die `DEFAULT_SIMILAR_PREFERENCE` wurde aktuell auf 3 gesetzt. Soll die auch bei 3 bleiben?

2024-01-22 14:54 UTC, mathun3003 commented on quotes_recommender/user_store/user_store_redis.py
> +    def clean_up_user_store(self, threshold: int = DEFAULT_SIMILAR_PREFERENCE) -> None:
Können die auch auf 5 setzen. Dann muss der User aber auch mindestens 3 bzw. 5 likes gesetzt haben. Dann implementiere ich das noch dass der user bei zu wenigen Likes eine Meldung angezeigt bekommt.

2024-01-23 09:57 UTC, Andyzilong commented on quotes_recommender/user_store/user_store_redis.py
> +    def clean_up_user_store(self, threshold: int = DEFAULT_SIMILAR_PREFERENCE) -> None:
Versuch das mal wenn das nicht zu viel aufwand dir bereitet

2024-01-26 08:50 UTC, Andyzilong approved these changes
Good Job Steve

2024-01-26 08:50 UTC, merged